### PR TITLE
Enhancment #6  Improve Footer UI

### PR DESCRIPTION
**Pull request by Atharva-04**
The footer features a sleek, gradient background with minimalistic white and gold accents for a luxurious feel. Social media icons with smooth hover effects and subtle shadows add interactivity, while the responsive design ensures elegance across all devices.
Before:
Orignal footer

After:
footer section

### CODE REVIEW

**Comment by Atharva-04** [comment]
@akhileshverma92  could you please review this PR, Thanks!

**Comment by akhileshverma92** [comment]
issue1


For desktop view port, it is good, but for mobile, I think some improvement ++
@Atharva-04

**Comment by Atharva-04** [comment]
Will look into it!

**Comment by Atharva-04** [comment]
@akhileshverma92 could you review this PR updated UI for footer.

**Comment by Atharva-04** [comment]
@akhileshverma92 Please review this PR.

**Comment by akhileshverma92** [comment]
issue3
review this and fix it

**Pull request closed without merging**
